/** \file
 *
 * \brief Definition of Bridge::CardType struct and related concepts
 */

#ifndef CARDTYPE_HH_
#define CARDTYPE_HH_

#include "enhanced_enum/enhanced_enum.hh"

#include <boost/operators.hpp>

#include <iosfwd>
#include <string_view>

namespace Bridge {

/*[[[cog
import cog
import enumecg
import enum
class Rank(enum.Enum):
  TWO = "2"
  THREE = "3"
  FOUR = "4"
  FIVE = "5"
  SIX = "6"
  SEVEN = "7"
  EIGHT = "8"
  NINE = "9"
  TEN = "10"
  JACK = "jack"
  QUEEN = "queen"
  KING = "king"
  ACE = "ace"
cog.out(enumecg.generate(Rank, primary_type="enhanced", documentation="doxygen"))
cog.out("\n\n")
class Suit(enum.Enum):
  CLUBS = "clubs"
  DIAMONDS = "diamonds"
  HEARTS = "hearts"
  SPADES = "spades"
cog.out(enumecg.generate(Suit, primary_type="enhanced", documentation="doxygen"))
]]]*/
/** \brief Label enum for \ref Rank
 */
enum class RankLabel {
    TWO,
    THREE,
    FOUR,
    FIVE,
    SIX,
    SEVEN,
    EIGHT,
    NINE,
    TEN,
    JACK,
    QUEEN,
    KING,
    ACE,
};

/** \brief Enhanced enum from label \ref RankLabel
 *
 * This enum was autogenerated for the enhanced enum library. Please see the
 * documentation for more information: https://enhanced-enum.readthedocs.io/
 */
struct Rank : ::enhanced_enum::enum_base<Rank, RankLabel, std::string_view> {
/// \cond internal
    using ::enhanced_enum::enum_base<Rank, RankLabel, std::string_view>::enum_base;
    static constexpr std::array values {
        value_type { "2" },
        value_type { "3" },
        value_type { "4" },
        value_type { "5" },
        value_type { "6" },
        value_type { "7" },
        value_type { "8" },
        value_type { "9" },
        value_type { "10" },
        value_type { "jack" },
        value_type { "queen" },
        value_type { "king" },
        value_type { "ace" },
    };
/// \endcond
};

/** \brief Promote \ref RankLabel to \ref Rank
 *
 * \param e Label enumerator
 *
 * \return The enhanced enumerator corresponding to \p e
 */
constexpr Rank enhance(RankLabel e) noexcept
{
    return e;
}

/** \brief Associate namespace for \ref Rank
 */
namespace Ranks {
/// \brief Value of enumerator \ref TWO
inline constexpr const Rank::value_type& TWO_VALUE { std::get<0>(Rank::values) };
/// \brief Value of enumerator \ref THREE
inline constexpr const Rank::value_type& THREE_VALUE { std::get<1>(Rank::values) };
/// \brief Value of enumerator \ref FOUR
inline constexpr const Rank::value_type& FOUR_VALUE { std::get<2>(Rank::values) };
/// \brief Value of enumerator \ref FIVE
inline constexpr const Rank::value_type& FIVE_VALUE { std::get<3>(Rank::values) };
/// \brief Value of enumerator \ref SIX
inline constexpr const Rank::value_type& SIX_VALUE { std::get<4>(Rank::values) };
/// \brief Value of enumerator \ref SEVEN
inline constexpr const Rank::value_type& SEVEN_VALUE { std::get<5>(Rank::values) };
/// \brief Value of enumerator \ref EIGHT
inline constexpr const Rank::value_type& EIGHT_VALUE { std::get<6>(Rank::values) };
/// \brief Value of enumerator \ref NINE
inline constexpr const Rank::value_type& NINE_VALUE { std::get<7>(Rank::values) };
/// \brief Value of enumerator \ref TEN
inline constexpr const Rank::value_type& TEN_VALUE { std::get<8>(Rank::values) };
/// \brief Value of enumerator \ref JACK
inline constexpr const Rank::value_type& JACK_VALUE { std::get<9>(Rank::values) };
/// \brief Value of enumerator \ref QUEEN
inline constexpr const Rank::value_type& QUEEN_VALUE { std::get<10>(Rank::values) };
/// \brief Value of enumerator \ref KING
inline constexpr const Rank::value_type& KING_VALUE { std::get<11>(Rank::values) };
/// \brief Value of enumerator \ref ACE
inline constexpr const Rank::value_type& ACE_VALUE { std::get<12>(Rank::values) };
/// \brief Enumerator of \ref Rank
inline constexpr Rank TWO { RankLabel::TWO };
/// \brief Enumerator of \ref Rank
inline constexpr Rank THREE { RankLabel::THREE };
/// \brief Enumerator of \ref Rank
inline constexpr Rank FOUR { RankLabel::FOUR };
/// \brief Enumerator of \ref Rank
inline constexpr Rank FIVE { RankLabel::FIVE };
/// \brief Enumerator of \ref Rank
inline constexpr Rank SIX { RankLabel::SIX };
/// \brief Enumerator of \ref Rank
inline constexpr Rank SEVEN { RankLabel::SEVEN };
/// \brief Enumerator of \ref Rank
inline constexpr Rank EIGHT { RankLabel::EIGHT };
/// \brief Enumerator of \ref Rank
inline constexpr Rank NINE { RankLabel::NINE };
/// \brief Enumerator of \ref Rank
inline constexpr Rank TEN { RankLabel::TEN };
/// \brief Enumerator of \ref Rank
inline constexpr Rank JACK { RankLabel::JACK };
/// \brief Enumerator of \ref Rank
inline constexpr Rank QUEEN { RankLabel::QUEEN };
/// \brief Enumerator of \ref Rank
inline constexpr Rank KING { RankLabel::KING };
/// \brief Enumerator of \ref Rank
inline constexpr Rank ACE { RankLabel::ACE };
}

/** \brief Label enum for \ref Suit
 */
enum class SuitLabel {
    CLUBS,
    DIAMONDS,
    HEARTS,
    SPADES,
};

/** \brief Enhanced enum from label \ref SuitLabel
 *
 * This enum was autogenerated for the enhanced enum library. Please see the
 * documentation for more information: https://enhanced-enum.readthedocs.io/
 */
struct Suit : ::enhanced_enum::enum_base<Suit, SuitLabel, std::string_view> {
/// \cond internal
    using ::enhanced_enum::enum_base<Suit, SuitLabel, std::string_view>::enum_base;
    static constexpr std::array values {
        value_type { "clubs" },
        value_type { "diamonds" },
        value_type { "hearts" },
        value_type { "spades" },
    };
/// \endcond
};

/** \brief Promote \ref SuitLabel to \ref Suit
 *
 * \param e Label enumerator
 *
 * \return The enhanced enumerator corresponding to \p e
 */
constexpr Suit enhance(SuitLabel e) noexcept
{
    return e;
}

/** \brief Associate namespace for \ref Suit
 */
namespace Suits {
/// \brief Value of enumerator \ref CLUBS
inline constexpr const Suit::value_type& CLUBS_VALUE { std::get<0>(Suit::values) };
/// \brief Value of enumerator \ref DIAMONDS
inline constexpr const Suit::value_type& DIAMONDS_VALUE { std::get<1>(Suit::values) };
/// \brief Value of enumerator \ref HEARTS
inline constexpr const Suit::value_type& HEARTS_VALUE { std::get<2>(Suit::values) };
/// \brief Value of enumerator \ref SPADES
inline constexpr const Suit::value_type& SPADES_VALUE { std::get<3>(Suit::values) };
/// \brief Enumerator of \ref Suit
inline constexpr Suit CLUBS { SuitLabel::CLUBS };
/// \brief Enumerator of \ref Suit
inline constexpr Suit DIAMONDS { SuitLabel::DIAMONDS };
/// \brief Enumerator of \ref Suit
inline constexpr Suit HEARTS { SuitLabel::HEARTS };
/// \brief Enumerator of \ref Suit
inline constexpr Suit SPADES { SuitLabel::SPADES };
}
//[[[end]]]

/** \brief Playing card type
 *
 * CardType objects are equality comparable. They compare equal when both rank
 * and suit are equal.
 *
 * \note Boost operators library is used to ensure that operator!= is
 * generated with usual semantics when operator== is supplied.
 */
struct CardType : private boost::equality_comparable<CardType> {
    Rank rank;  ///< \brief Rank of the card
    Suit suit;  ///< \brief Suit of the card

    CardType() = default;

    /** \brief Create new card type
     *
     * \param rank the rank of the card
     * \param suit the suit of the card
     */
    constexpr CardType(Rank rank, Suit suit) :
        rank {rank},
        suit {suit}
    {
    }
};

/** \brief Equality operator for card types
 *
 * \sa CardType
 */
bool operator==(const CardType&, const CardType&);

/** \brief Output a Rank to stream
 *
 * \param os the output stream
 * \param rank the rank to output
 *
 * \return parameter \p os
 */
std::ostream& operator<<(std::ostream& os, Rank rank);

/** \brief Output a Suit to stream
 *
 * \param os the output stream
 * \param suit the suit to output
 *
 * \return parameter \p os
 */
std::ostream& operator<<(std::ostream& os, Suit suit);

/** \brief Output a CardType to stream
 *
 * \param os the output stream
 * \param cardType the card type to output
 *
 * \return parameter \p os
 */
std::ostream& operator<<(std::ostream& os, CardType cardType);

}

#endif // CARDTYPE_HH_
